FROM node:24-alpine AS build

WORKDIR /auth-server

COPY package.json package-lock.json ./

RUN npm install

COPY . .

RUN npm run build

FROM node:24-alpine

WORKDIR /auth-server

COPY package.json package-lock.json ./

RUN npm ci --only=production

COPY --from=build /auth-server/dist ./dist

CMD [ "node", "dist/index.js" ]
